In [5]:
from sklearn.neighbors import BallTree
import numpy as np
from random import sample
from numpy.random import uniform 
import pandas as pd
D = pd.read_csv('compresive_strength_concrete.csv')

In [4]:
from hopkins import Hopkins
hop = Hopkins(D,200)

In [14]:
l = []
for i in range (0,100):
    l.append(hop.evalue())
    
np.mean(l)

0.9129814310007525

In [15]:
l

[array([0.90599406]),
 array([0.91950444]),
 array([0.90348013]),
 array([0.91329616]),
 array([0.92327786]),
 array([0.90631184]),
 array([0.9049672]),
 array([0.91083851]),
 array([0.90552864]),
 array([0.91042448]),
 array([0.90549122]),
 array([0.90814493]),
 array([0.91890298]),
 array([0.91178851]),
 array([0.92082992]),
 array([0.91536874]),
 array([0.91073896]),
 array([0.916064]),
 array([0.91856121]),
 array([0.91061661]),
 array([0.91628869]),
 array([0.90321464]),
 array([0.91174381]),
 array([0.90538299]),
 array([0.91467053]),
 array([0.9072381]),
 array([0.91029978]),
 array([0.92260754]),
 array([0.90599988]),
 array([0.91721685]),
 array([0.91954725]),
 array([0.91546501]),
 array([0.91842195]),
 array([0.91547123]),
 array([0.90448573]),
 array([0.91511656]),
 array([0.91490228]),
 array([0.91738607]),
 array([0.91430285]),
 array([0.9186276]),
 array([0.92391915]),
 array([0.90783985]),
 array([0.90821434]),
 array([0.91467866]),
 array([0.91512143]),
 array([0.90483

In [64]:
dist, ind = tree.query(P, k=1)
#print(dist)
#print(ind)
list(np.concatenate(ind))

[812,
 741,
 322,
 1005,
 986,
 83,
 748,
 517,
 19,
 242,
 918,
 800,
 954,
 906,
 979,
 968,
 831,
 165,
 758,
 36]

In [66]:
D_ = D.drop(list(np.concatenate(ind)))
D_

cement   slag  flyash  water  superplasticizer  coarseaggregate  \
0      540.0    0.0     0.0  162.0               2.5           1040.0   
1      540.0    0.0     0.0  162.0               2.5           1055.0   
2      332.5  142.5     0.0  228.0               0.0            932.0   
3      332.5  142.5     0.0  228.0               0.0            932.0   
4      198.6  132.4     0.0  192.0               0.0            978.4   
5      266.0  114.0     0.0  228.0               0.0            932.0   
6      380.0   95.0     0.0  228.0               0.0            932.0   
7      380.0   95.0     0.0  228.0               0.0            932.0   
8      266.0  114.0     0.0  228.0               0.0            932.0   
9      475.0    0.0     0.0  228.0               0.0            932.0   
10     198.6  132.4     0.0  192.0               0.0            978.4   
11     198.6  132.4     0.0  192.0               0.0            978.4   
12     427.5   47.5     0.0  228.0               0.0            932.0   
13     190.0  190.0     0.0  228.0               0.0            932.0   
14     304.0   76.0     0.0  228.0               0.0            932.0   
15     380.0    0.0     0.0  228.0               0.0            932.0   
16     139.6  209.4     0.0  192.0               0.0           1047.0   
17     342.0   38.0     0.0  228.0               0.0            932.0   
18     380.0   95.0     0.0  228.0               0.0            932.0   
20     427.5   47.5     0.0  228.0               0.0            932.0   
21     139.6  209.4     0.0  192.0               0.0           1047.0   
22     139.6  209.4     0.0  192.0               0.0           1047.0   
23     139.6  209.4     0.0  192.0               0.0           1047.0   
24     380.0    0.0     0.0  228.0               0.0            932.0   
25     380.0    0.0     0.0  228.0               0.0            932.0   
26     380.0   95.0     0.0  228.0               0.0            932.0   
27     342.0   38.0     0.0  228.0               0.0            932.0   
28     427.5   47.5     0.0  228.0               0.0            932.0   
29     475.0    0.0     0.0  228.0               0.0            932.0   
30     304.0   76.0     0.0  228.0               0.0            932.0   
...      ...    ...     ...    ...               ...              ...   
999    150.9    0.0   183.9  166.6              11.6            991.2   
1000   141.9  166.6   129.7  173.5              10.9            882.6   
1001   297.8  137.2   106.9  201.3               6.0            878.4   
1002   321.3  164.2     0.0  190.5               4.6            870.0   
1003   366.0  187.0     0.0  191.3               6.6            824.3   
1004   279.8  128.9   100.4  172.4               9.5            825.1   
1006   164.6    0.0   150.4  181.6              11.7           1023.3   
1007   155.6  243.5     0.0  180.3              10.7           1022.0   
1008   160.2  188.0   146.4  203.2              11.3            828.7   
1009   298.1    0.0   107.0  186.4               6.1            879.0   
1010   317.9    0.0   126.5  209.7               5.7            860.5   
1011   287.3  120.5    93.9  187.6               9.2            904.4   
1012   325.6  166.4     0.0  174.0               8.9            881.6   
1013   355.9    0.0   141.6  193.3              11.0            801.4   
1014   132.0  206.5   160.9  178.9               5.5            866.9   
1015   322.5  148.6     0.0  185.8               8.5            951.0   
1016   164.2    0.0   200.1  181.2              12.6            849.3   
1017   313.8    0.0   112.6  169.9              10.1            925.3   
1018   321.4    0.0   127.9  182.5              11.5            870.1   
1019   139.7  163.9   127.7  236.7               5.8            868.6   
1020   288.4  121.0     0.0  177.4               7.0            907.9   
1021   298.2    0.0   107.0  209.7              11.1            879.6   
1022   264.5  111.0    86.5  195.5               5.9            

In [75]:
tree = BallTree(D_,leaf_size=2)
dist, ind = tree.query(P, k=2)
print(dist[:,1])
dist

[33.79001184 24.60370704 24.59658716 38.86       36.91372238  0.
  8.19283223 22.10452442 90.000845   23.32303797 31.20224511  2.48251888
 60.48115409 25.38531859 41.23833168 38.56213298 55.66087405 57.2475327
 14.80324627 62.07448429]


array([[33.71205274, 33.79001184],
       [ 8.80241444, 24.60370704],
       [18.4899973 , 24.59658716],
       [ 0.84852814, 38.86      ],
       [ 0.51961524, 36.91372238],
       [ 0.        ,  0.        ],
       [ 7.93176525,  8.19283223],
       [ 6.57635157, 22.10452442],
       [67.17967252, 90.000845  ],
       [ 2.27290563, 23.32303797],
       [ 0.6244998 , 31.20224511],
       [ 2.4530797 ,  2.48251888],
       [ 0.82462113, 60.48115409],
       [ 0.94339811, 25.38531859],
       [ 0.60835845, 41.23833168],
       [ 0.47958315, 38.56213298],
       [ 0.6       , 55.66087405],
       [35.04625515, 57.2475327 ],
       [ 8.26801064, 14.80324627],
       [21.34461056, 62.07448429]])